import { SideBar } from "@/components/SideBar/SideBar";
import Header from "./header";
import { ToastContainer } from 'react-toastify';
export const metadata = {
   title: "FotoSelect",
   description: "Generated by create next app",
};

export default function PrivateLayout({ children }) {
   return (
      <>
         <Header />
         <div className="layout flex flex-row h-[calc(100vh-4rem)] gap-2 p-2 bg-[var(--dashboard-background)]">
            <SideBar />
            {children}
         </div>
         <ToastContainer position="bottom-right"/>
      </>
   );
}