import { SideBar } from "@/components/SideBar/SideBar";
import Header from "./header";
import { ToastContainer } from 'react-toastify';
import { ConfirmModal } from "@/components/modals/ConfirmDecision/ConfirmModal";


export const metadata = {
   title: "FotoSelect",
   description: "Generated by create next app",
};

export default function PrivateLayout({ children }) {
   return (
      <>
         <Header />
         <main className="layout flex flex-row h-[calc(100vh-4rem)] gap-2 p-2 bg-[var(--dashboard-background)]">
            <SideBar />
            <section className="flex flex-col items-center gap-3 h-[calc(100vh-4rem)] -mt-2 w-full bg-[var(--dashboard-background)] shadow-[0_0_3_3px_var(--shadow)] rounded-xl pt-3 px-10 overflow-y-auto">
               {children}
            </section>
            <ConfirmModal />
         </main>
         <ToastContainer position="bottom-right" />
      </>
   );
}