import Header from "./header";

export const metadata = {
   title: "FotoSelect",
   description: "Generated by create next app",
};

export default function PublicLayout({ children }) {
   return (
      <>
         <Header />
         {children}
      </>
   );
}
