import Header from "./header";
import { ToastContainer } from 'react-toastify';
export const metadata = {
   title: "FotoSelect",
   description: "Generated by create next app",
};

export default function PublicLayout({ children }) {
   return (
      <>
         <Header />
         {children}
         <ToastContainer position="bottom-right"/>
      </>
   );
}
